version: '3'
services:
  app:
    build: ./
    ports:
      - "9011:9011"
    volumes:
      - ./:/app
      - /app/target
      - /app/project/project
      - /app/project/target
    container_name: play-docker
    stdin_open: true
    tty: true
    env_file:
      - ./.env